fix: csv dataobject import reload column configuration
Error: CSV DataObject import, tab panel "CSV Settings", button "Reload column configuration" triggered error "Uncaught TypeError: this.callback is undefined" in updateColumnConfig
Caused by: Argument "showReload" was missing in constructor call
Introduced by: 62202949a129c806754f57c15498a60bf753943b
Relates to: Issue #6462