fix: WebsiteSetting SiteId and Language should be nullable
Error: Can't create a global WebsiteSetting without selecting a Site and Language
Caused by: Option setters don't allow null
Resolved with: Allowing null, changing default language to null (to avoid a uninitialized property when configured from code)

Also: added a `return $this` to setLanguage()